name: Docker Build with Discord Notification

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'
  schedule:
    - cron: '0 12 15 * *'
  workflow_dispatch:

jobs:
  call-docker-build:
    name: Call Docker Build
    uses: bretfisher/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      packages: write 
      pull-requests: write    
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      dockerhub-enable: true
      ghcr-enable: true
      platforms: linux/amd64,linux/arm64

  discord-notify:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    needs: call-docker-build
    steps:
      - name: Send Discord Message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: "Docker build complete for ${{ github.repository }} on commit ${{ github.sha }}."
